// Meertaligheid voor de publieke site: PL (bron), EN, NL, ES.
const LANGS = ['pl', 'en', 'nl', 'es'];
const LANGMETA = {
  pl: { flag: '🇵🇱', label: 'PL', name: 'Polski' },
  en: { flag: '🇬🇧', label: 'EN', name: 'English' },
  nl: { flag: '🇳🇱', label: 'NL', name: 'Nederlands' },
  es: { flag: '🇪🇸', label: 'ES', name: 'Español' }
};

const T = {
  pl: {
    topTagline: 'Zaufanie. Opieka. Przyszłość.', location: 'Warszawa, Polska',
    nav: { home: 'Strona główna', about: 'O nas', institutions: 'Dla instytucji', candidates: 'Dla profesjonalistów', academy: 'Akademia', housing: 'Mieszkania', poland: 'Polska', contact: 'Kontakt', portal: 'Portal' },
    hero: { h1: ['Kompleksowe', 'rozwiązania w opiece zdrowotnej', 'dla Polski'], p: 'Łączymy wykwalifikowanych specjalistów z instytucjami medycznymi w całej Polsce. Rekrutacja, legalizacja, zakwaterowanie i wsparcie — wszystko w jednym miejscu.', bullets: ['Rekrutacja międzynarodowa', 'Legalizacja i dokumenty', 'Kursy języka polskiego', 'Wsparcie po przyjeździe', 'Zakwaterowanie', 'Integracja i adaptacja', 'Opieka koordynatora', 'Dla profesjonalistów i rodzin'], btnInst: 'Dla instytucji', btnProf: 'Dla profesjonalistów', btnMeet: '▣ Umów spotkanie', badge: 'Z miłości do ludzi, z myślą o przyszłości' },
    specs: ['Lekarze ogólni', 'Specjaliści', 'Stomatolodzy', 'Pielęgniarki', 'Psycholodzy', 'Fizjoterapeuci', 'Farmaceuci', 'Higieniści stomatologiczne', 'Opiekunowie medyczni', 'I więcej specjalizacji'],
    cards: [
      { tag: 'DLA PROFESJONALISTÓW', h: 'Pracuj w Polsce z nami', items: ['Atrakcyjne zarobki', 'Legalna praca i pełne wsparcie', 'Pomoc w uznaniu kwalifikacji', 'Organizacja zakwaterowania', 'Wsparcie dla Ciebie i Twojej rodziny'], btn: 'ZACZNIJ SWOJĄ PRZYSZŁOŚĆ' },
      { tag: 'DLA INSTYTUCJI', h: 'Skuteczne rozwiązania dla Twojej placówki', items: ['Selekcja wykwalifikowanych kandydatów', 'Szkolenia językowe i kulturowe', 'Wsparcie w formalnościach', 'Uznanie kwalifikacji', 'Stała opieka koordynatora'], btn: 'POPROŚ O OFERTĘ' },
      { tag: 'AKADEMIA HONOR CARE', h: 'Szkolenia i rozwój zawodowy', items: ['Kursy języka polskiego (A1–B2)', 'Terminy i skróty medyczne', 'Kultura i system pracy w Polsce', 'Przygotowanie do pracy', 'Szkolenia online z Kolumbii'], btn: 'PRZEJDŹ DO AKADEMII' },
      { tag: 'MIESZKANIA', h: 'Komfort i bezpieczeństwo', items: ['Nowoczesne i w pełni wyposażone', 'Blisko miejsc pracy', 'Wsparcie w integracji', 'Bezpieczne i sprawdzone', 'Dla rodzin i osób indywidualnych'], btn: 'ZOBACZ MIESZKANIA' }
    ],
    why: { eyebrow: 'DLACZEGO POLSKA?', h2: ['Stabilna przyszłość', 'w sercu Europy'], p: 'Polska oferuje doskonałe możliwości rozwoju zawodowego, bezpieczeństwo i wysoką jakość życia.', btn: 'DOWIEDZ SIĘ WIĘCEJ', stats: ['Specjalistów już pracuje w Polsce', 'Placówek medycznych współpracuje z nami', 'Lat doświadczenia w rekrutacji międzynarodowej', 'Kraje połączone jednym celem'] },
    partnersTitle: 'NASI PARTNERZY',
    footer: { tagline: 'Budujemy mosty między Kolumbią a Polską, łącząc talenty, możliwości i przyszłość.', quick: 'Szybkie linki', officeNL: 'Polska – Biuro Główne', officeCO: 'Kolumbia', hoursNL: 'Pon – Pt: 9:00 – 17:00', hoursCO: 'Pon – Pt: 8:00 – 16:00', newsletter: 'Newsletter', newsletterText: 'Zapisz się, aby otrzymywać aktualności i oferty.', newsletterPh: 'Twój e-mail', rights: 'Wszelkie prawa zastrzeżone.', privacy: 'Polityka prywatności', terms: 'Regulamin' },
    toast: 'Dziękujemy! Zapisano do newslettera.',
    notFound: 'Strona nie została znaleziona.',
    contactIntro: 'Skontaktuj się z nami w sprawie współpracy lub rekrutacji.',
    pages: {
      about: { intro: 'Honor Care International łączy Kolumbię i Polskę poprzez profesjonalną rekrutację, edukację i opiekę koordynacyjną.', panels: [['Nasza misja', 'Tworzymy bezpieczne i godne ścieżki kariery dla specjalistów medycznych, odpowiadając na realne potrzeby polskiego systemu opieki zdrowotnej.'], ['Dwa kraje, jeden cel', 'Działamy w Kolumbii i w Polsce, łącząc rekrutację u źródła z pełnym wsparciem na miejscu.'], ['Pełna ścieżka', 'Od selekcji i weryfikacji dyplomów, przez naukę języka, aż po zakwaterowanie i integrację — prowadzimy kandydata na każdym etapie.'], ['Wartości', 'Zaufanie, transparentność i szacunek dla człowieka są fundamentem każdej współpracy.'], ['Zgodność prawna', 'Pracujemy zgodnie z polskim prawem pracy, przepisami o legalizacji pobytu oraz RODO.'], ['Dlaczego my', 'Jeden partner odpowiedzialny za cały proces — bez pośredników i bez niespodzianek.']] },
      institutions: { intro: 'Pomagamy placówkom medycznym w Polsce skutecznie rozwiązać braki kadrowe.', panels: [['Analiza potrzeb', 'Określamy profil poszukiwanych specjalistów, liczebność i harmonogram wdrożenia.'], ['Selekcja kandydatów', 'Prezentujemy wyłącznie zweryfikowanych kandydatów z potwierdzonymi kwalifikacjami.'], ['Legalizacja i dokumenty', 'Przejmujemy formalności wizowe, pobytowe i związane z uznaniem kwalifikacji.'], ['Szkolenia językowe', 'Kandydaci uczą się języka polskiego i terminologii medycznej jeszcze przed przyjazdem.'], ['Zakwaterowanie', 'Organizujemy komfortowe mieszkania blisko miejsca pracy.'], ['Stała opieka koordynatora', 'Dedykowany koordynator wspiera placówkę i pracownika przez cały okres współpracy.']] },
      candidates: { intro: 'Tworzymy bezpieczną drogę do pracy w Polsce dla profesjonalistów medycznych z Kolumbii.', panels: [['Proces rekrutacji', 'Przejrzysta selekcja i jasne warunki współpracy od pierwszego kontaktu.'], ['Uznanie kwalifikacji', 'Pomagamy w nostryfikacji dyplomu i potwierdzeniu uprawnień zawodowych.'], ['Nauka języka', 'Kursy polskiego od poziomu A1 do B2 wraz z terminologią medyczną.'], ['Przyjazd i adaptacja', 'Wsparcie przy przeprowadzce, formalnościach i pierwszych krokach w Polsce.'], ['Zakwaterowanie', 'Gotowe, umeblowane mieszkania w bezpiecznych lokalizacjach.'], ['Wsparcie rodziny', 'Pomoc w integracji rodziny, szkole dla dzieci i codziennych sprawach.']] },
      academy: { intro: 'Akademia Honor Care przygotowuje kandydatów językowo, zawodowo i kulturowo.', panels: [['Kurs A1–A2', 'Podstawy języka polskiego w mowie i piśmie, gotowe na codzienne sytuacje.'], ['Kurs B1–B2', 'Zaawansowana komunikacja niezbędna w pracy z pacjentem i zespołem.'], ['Terminologia medyczna', 'Specjalistyczne słownictwo dla pielęgniarek, lekarzy i opiekunów.'], ['Szkolenia online', 'Elastyczna nauka zdalna jeszcze przed przyjazdem do Polski.'], ['Egzaminy i certyfikaty', 'Przygotowanie do egzaminów językowych i uznanych certyfikatów.'], ['Mentoring', 'Indywidualne wsparcie mentora przez cały okres nauki.']] },
      housing: { intro: 'Organizujemy komfortowe mieszkania i wsparcie integracyjne.', panels: [['Nowoczesne mieszkania', 'Wygodne, w pełni wyposażone lokale gotowe na przyjazd.'], ['Lokalizacja', 'Blisko miejsc pracy i komunikacji miejskiej.'], ['Dla rodzin', 'Mieszkania dostosowane do potrzeb rodzin z dziećmi.'], ['Umeblowanie', 'Pełne umeblowanie i wyposażenie od pierwszego dnia.'], ['Wsparcie administracyjne', 'Pomoc przy umowach, mediach i meldunku.'], ['Bezpieczeństwo', 'Sprawdzone, bezpieczne dzielnice i rzetelni wynajmujący.']] },
      poland: { intro: 'Polska oferuje stabilność, rozwój zawodowy i wysoką jakość życia.', panels: [['Stabilna gospodarka', 'Jeden z najszybciej rozwijających się rynków pracy w Europie.'], ['System opieki zdrowotnej', 'Rosnące zapotrzebowanie na wykwalifikowany personel medyczny.'], ['Jakość życia', 'Bezpieczeństwo, dobra infrastruktura i przystępne koszty życia.'], ['Kultura', 'Bogata historia, otwartość i serdeczność mieszkańców.'], ['Rozwój zawodowy', 'Realne ścieżki awansu i stałego doskonalenia.'], ['Centrum Europy', 'Dogodna lokalizacja i łatwy dostęp do całego kontynentu.']] }
    }
  },

  en: {
    topTagline: 'Trust. Care. Future.', location: 'Warsaw, Poland',
    nav: { home: 'Home', about: 'About us', institutions: 'For institutions', candidates: 'For professionals', academy: 'Academy', housing: 'Housing', poland: 'Poland', contact: 'Contact', portal: 'Portal' },
    hero: { h1: ['Comprehensive', 'healthcare solutions', 'for Poland'], p: 'We connect qualified specialists with medical institutions across Poland. Recruitment, legalisation, housing and support — all in one place.', bullets: ['International recruitment', 'Legalisation & documents', 'Polish language courses', 'Post-arrival support', 'Housing', 'Integration & adaptation', 'Coordinator care', 'For professionals & families'], btnInst: 'For institutions', btnProf: 'For professionals', btnMeet: '▣ Book a meeting', badge: 'Out of love for people, with the future in mind' },
    specs: ['General practitioners', 'Specialists', 'Dentists', 'Nurses', 'Psychologists', 'Physiotherapists', 'Pharmacists', 'Dental hygienists', 'Medical caregivers', 'And more specialties'],
    cards: [
      { tag: 'FOR PROFESSIONALS', h: 'Work in Poland with us', items: ['Attractive salary', 'Legal work and full support', 'Help recognising qualifications', 'Housing arranged for you', 'Support for you and your family'], btn: 'START YOUR FUTURE' },
      { tag: 'FOR INSTITUTIONS', h: 'Effective solutions for your facility', items: ['Selection of qualified candidates', 'Language and cultural training', 'Support with formalities', 'Recognition of qualifications', 'Ongoing coordinator support'], btn: 'REQUEST AN OFFER' },
      { tag: 'HONOR CARE ACADEMY', h: 'Training and professional development', items: ['Polish language courses (A1–B2)', 'Medical terms and abbreviations', 'Polish work culture and system', 'Job preparation', 'Online training from Colombia'], btn: 'GO TO THE ACADEMY' },
      { tag: 'HOUSING', h: 'Comfort and safety', items: ['Modern and fully furnished', 'Close to workplaces', 'Integration support', 'Safe and verified', 'For families and individuals'], btn: 'VIEW HOUSING' }
    ],
    why: { eyebrow: 'WHY POLAND?', h2: ['A stable future', 'in the heart of Europe'], p: 'Poland offers excellent opportunities for professional growth, safety and a high quality of life.', btn: 'LEARN MORE', stats: ['Specialists already working in Poland', 'Medical facilities working with us', 'Years of experience in international recruitment', 'Countries united by one goal'] },
    partnersTitle: 'OUR PARTNERS',
    footer: { tagline: 'We build bridges between Colombia and Poland, connecting talent, opportunity and the future.', quick: 'Quick links', officeNL: 'Poland – Head Office', officeCO: 'Colombia', hoursNL: 'Mon – Fri: 9:00 – 17:00', hoursCO: 'Mon – Fri: 8:00 – 16:00', newsletter: 'Newsletter', newsletterText: 'Sign up to receive news and offers.', newsletterPh: 'Your e-mail', rights: 'All rights reserved.', privacy: 'Privacy policy', terms: 'Terms' },
    toast: "Thank you! You're subscribed to the newsletter.",
    notFound: 'Page not found.',
    contactIntro: 'Get in touch with us about cooperation or recruitment.',
    pages: {
      about: { intro: 'Honor Care International connects Colombia and Poland through professional recruitment, education and coordinated care.', panels: [['Our mission', 'We create safe and dignified career paths for medical specialists, meeting the real needs of the Polish healthcare system.'], ['Two countries, one goal', 'We operate in Colombia and Poland, combining recruitment at the source with full on-site support.'], ['The full journey', 'From selection and diploma verification, through language learning, to housing and integration — we guide the candidate at every step.'], ['Values', 'Trust, transparency and respect for people are the foundation of every partnership.'], ['Legal compliance', 'We work in compliance with Polish labour law, residence legalisation rules and the GDPR.'], ['Why us', 'One partner responsible for the entire process — no middlemen, no surprises.']] },
      institutions: { intro: 'We help medical facilities in Poland effectively solve staff shortages.', panels: [['Needs analysis', 'We define the profile of the specialists needed, the numbers and the implementation timeline.'], ['Candidate selection', 'We present only verified candidates with confirmed qualifications.'], ['Legalisation & documents', 'We handle visa, residence and qualification-recognition formalities.'], ['Language training', 'Candidates learn Polish and medical terminology before they even arrive.'], ['Housing', 'We arrange comfortable housing close to the workplace.'], ['Ongoing coordinator support', 'A dedicated coordinator supports the facility and the employee throughout the cooperation.']] },
      candidates: { intro: 'We create a safe path to working in Poland for medical professionals from Colombia.', panels: [['Recruitment process', 'Transparent selection and clear terms of cooperation from the first contact.'], ['Recognition of qualifications', 'We help with diploma recognition and confirmation of professional rights.'], ['Language learning', 'Polish courses from A1 to B2 level, including medical terminology.'], ['Arrival & adaptation', 'Support with the move, formalities and your first steps in Poland.'], ['Housing', 'Ready, furnished apartments in safe locations.'], ['Family support', 'Help with family integration, schooling for children and everyday matters.']] },
      academy: { intro: 'The Honor Care Academy prepares candidates linguistically, professionally and culturally.', panels: [['A1–A2 course', 'Polish basics in speech and writing, ready for everyday situations.'], ['B1–B2 course', 'Advanced communication essential for working with patients and teams.'], ['Medical terminology', 'Specialist vocabulary for nurses, doctors and caregivers.'], ['Online training', 'Flexible remote learning even before arriving in Poland.'], ['Exams & certificates', 'Preparation for language exams and recognised certificates.'], ['Mentoring', 'Individual mentor support throughout the learning period.']] },
      housing: { intro: 'We arrange comfortable housing and integration support.', panels: [['Modern apartments', 'Comfortable, fully equipped places ready for arrival.'], ['Location', 'Close to workplaces and public transport.'], ['For families', 'Apartments adapted to the needs of families with children.'], ['Furnishing', 'Full furnishing and equipment from day one.'], ['Administrative support', 'Help with contracts, utilities and registration.'], ['Safety', 'Verified, safe neighbourhoods and reliable landlords.']] },
      poland: { intro: 'Poland offers stability, professional growth and a high quality of life.', panels: [['Stable economy', 'One of the fastest-growing labour markets in Europe.'], ['Healthcare system', 'Growing demand for qualified medical staff.'], ['Quality of life', 'Safety, good infrastructure and affordable living costs.'], ['Culture', 'Rich history and the openness and warmth of its people.'], ['Professional growth', 'Real paths for promotion and continuous development.'], ['Heart of Europe', 'A convenient location with easy access to the whole continent.']] }
    }
  },

  nl: {
    topTagline: 'Vertrouwen. Zorg. Toekomst.', location: 'Warschau, Polen',
    nav: { home: 'Home', about: 'Over ons', institutions: 'Voor instellingen', candidates: 'Voor professionals', academy: 'Academie', housing: 'Huisvesting', poland: 'Polen', contact: 'Contact', portal: 'Portal' },
    hero: { h1: ['Complete', 'zorgoplossingen', 'voor Polen'], p: 'Wij verbinden gekwalificeerde specialisten met zorginstellingen in heel Polen. Werving, legalisatie, huisvesting en begeleiding — alles op één plek.', bullets: ['Internationale werving', 'Legalisatie & documenten', 'Cursussen Pools', 'Begeleiding na aankomst', 'Huisvesting', 'Integratie & aanpassing', 'Zorg van een coördinator', 'Voor professionals & gezinnen'], btnInst: 'Voor instellingen', btnProf: 'Voor professionals', btnMeet: '▣ Plan een gesprek', badge: 'Uit liefde voor mensen, met het oog op de toekomst' },
    specs: ['Huisartsen', 'Specialisten', 'Tandartsen', 'Verpleegkundigen', 'Psychologen', 'Fysiotherapeuten', 'Apothekers', 'Mondhygiënisten', 'Zorgverleners', 'En meer specialismen'],
    cards: [
      { tag: 'VOOR PROFESSIONALS', h: 'Werk met ons in Polen', items: ['Aantrekkelijk salaris', 'Legaal werk en volledige begeleiding', 'Hulp bij erkenning van diploma\u2019s', 'Huisvesting geregeld', 'Steun voor jou en je gezin'], btn: 'START JE TOEKOMST' },
      { tag: 'VOOR INSTELLINGEN', h: 'Doeltreffende oplossingen voor uw instelling', items: ['Selectie van gekwalificeerde kandidaten', 'Taal- en cultuurtraining', 'Ondersteuning bij formaliteiten', 'Erkenning van kwalificaties', 'Vaste begeleiding door coördinator'], btn: 'VRAAG EEN OFFERTE AAN' },
      { tag: 'HONOR CARE ACADEMIE', h: 'Training en professionele ontwikkeling', items: ['Cursussen Pools (A1–B2)', 'Medische termen en afkortingen', 'Werkcultuur en -systeem in Polen', 'Voorbereiding op het werk', 'Online training vanuit Colombia'], btn: 'NAAR DE ACADEMIE' },
      { tag: 'HUISVESTING', h: 'Comfort en veiligheid', items: ['Modern en volledig ingericht', 'Dicht bij het werk', 'Ondersteuning bij integratie', 'Veilig en gecontroleerd', 'Voor gezinnen en alleenstaanden'], btn: 'BEKIJK WONINGEN' }
    ],
    why: { eyebrow: 'WAAROM POLEN?', h2: ['Een stabiele toekomst', 'in het hart van Europa'], p: 'Polen biedt uitstekende kansen voor professionele groei, veiligheid en een hoge levenskwaliteit.', btn: 'MEER WETEN', stats: ['Specialisten werken al in Polen', 'Zorginstellingen werken met ons samen', 'Jaar ervaring in internationale werving', 'Landen verbonden door één doel'] },
    partnersTitle: 'ONZE PARTNERS',
    footer: { tagline: 'Wij bouwen bruggen tussen Colombia en Polen en verbinden talent, kansen en toekomst.', quick: 'Snelle links', officeNL: 'Polen – Hoofdkantoor', officeCO: 'Colombia', hoursNL: 'Ma – Vr: 9:00 – 17:00', hoursCO: 'Ma – Vr: 8:00 – 16:00', newsletter: 'Nieuwsbrief', newsletterText: 'Schrijf je in voor nieuws en aanbiedingen.', newsletterPh: 'Je e-mail', rights: 'Alle rechten voorbehouden.', privacy: 'Privacybeleid', terms: 'Voorwaarden' },
    toast: 'Bedankt! Je bent ingeschreven voor de nieuwsbrief.',
    notFound: 'Pagina niet gevonden.',
    contactIntro: 'Neem contact met ons op over samenwerking of werving.',
    pages: {
      about: { intro: 'Honor Care International verbindt Colombia en Polen via professionele werving, opleiding en gecoördineerde begeleiding.', panels: [['Onze missie', 'Wij creëren veilige en waardige loopbaanpaden voor medische specialisten en spelen in op de werkelijke behoeften van de Poolse zorg.'], ['Twee landen, één doel', 'We zijn actief in Colombia en Polen en combineren werving aan de bron met volledige ondersteuning ter plaatse.'], ['Het volledige traject', 'Van selectie en diplomacontrole, via taalverwerving, tot huisvesting en integratie — we begeleiden de kandidaat in elke fase.'], ['Waarden', 'Vertrouwen, transparantie en respect voor de mens vormen de basis van elke samenwerking.'], ['Juridische naleving', 'We werken conform het Poolse arbeidsrecht, de regels voor verblijfslegalisatie en de AVG.'], ['Waarom wij', 'Eén partner verantwoordelijk voor het hele proces — geen tussenpersonen, geen verrassingen.']] },
      institutions: { intro: 'Wij helpen zorginstellingen in Polen personeelstekorten doeltreffend op te lossen.', panels: [['Behoefteanalyse', 'We bepalen het profiel van de gezochte specialisten, de aantallen en de planning.'], ['Kandidaatselectie', 'We presenteren uitsluitend geverifieerde kandidaten met bevestigde kwalificaties.'], ['Legalisatie & documenten', 'Wij nemen de visum-, verblijfs- en diploma-erkenningsformaliteiten over.'], ['Taaltraining', 'Kandidaten leren Pools en medische terminologie nog vóór hun aankomst.'], ['Huisvesting', 'Wij regelen comfortabele woningen dicht bij het werk.'], ['Vaste begeleiding door coördinator', 'Een vaste coördinator ondersteunt de instelling en de medewerker gedurende de hele samenwerking.']] },
      candidates: { intro: 'Wij creëren een veilige weg naar werk in Polen voor medische professionals uit Colombia.', panels: [['Wervingsproces', 'Transparante selectie en duidelijke samenwerkingsvoorwaarden vanaf het eerste contact.'], ['Erkenning van kwalificaties', 'Wij helpen bij diploma-erkenning en bevestiging van beroepsbevoegdheden.'], ['Taal leren', 'Cursussen Pools van niveau A1 tot B2, inclusief medische terminologie.'], ['Aankomst & aanpassing', 'Begeleiding bij de verhuizing, formaliteiten en eerste stappen in Polen.'], ['Huisvesting', 'Kant-en-klare, gemeubileerde woningen op veilige locaties.'], ['Gezinsondersteuning', 'Hulp bij gezinsintegratie, school voor de kinderen en dagelijkse zaken.']] },
      academy: { intro: 'De Honor Care Academie bereidt kandidaten talig, professioneel en cultureel voor.', panels: [['Cursus A1–A2', 'Basis Pools in spraak en schrift, klaar voor dagelijkse situaties.'], ['Cursus B1–B2', 'Gevorderde communicatie die nodig is in het werk met patiënten en team.'], ['Medische terminologie', 'Vakspecifiek vocabulaire voor verpleegkundigen, artsen en verzorgenden.'], ['Online training', 'Flexibel leren op afstand, nog vóór de aankomst in Polen.'], ['Examens & certificaten', 'Voorbereiding op taalexamens en erkende certificaten.'], ['Mentoring', 'Individuele mentorbegeleiding gedurende de hele opleiding.']] },
      housing: { intro: 'Wij regelen comfortabele woningen en integratieondersteuning.', panels: [['Moderne woningen', 'Comfortabele, volledig uitgeruste woningen klaar voor aankomst.'], ['Locatie', 'Dicht bij het werk en openbaar vervoer.'], ['Voor gezinnen', 'Woningen afgestemd op gezinnen met kinderen.'], ['Inrichting', 'Volledige inrichting en uitrusting vanaf dag één.'], ['Administratieve ondersteuning', 'Hulp bij contracten, nutsvoorzieningen en inschrijving.'], ['Veiligheid', 'Gecontroleerde, veilige buurten en betrouwbare verhuurders.']] },
      poland: { intro: 'Polen biedt stabiliteit, professionele groei en een hoge levenskwaliteit.', panels: [['Stabiele economie', 'Een van de snelst groeiende arbeidsmarkten van Europa.'], ['Zorgstelsel', 'Groeiende vraag naar gekwalificeerd medisch personeel.'], ['Levenskwaliteit', 'Veiligheid, goede infrastructuur en betaalbare kosten van levensonderhoud.'], ['Cultuur', 'Rijke geschiedenis en de openheid en hartelijkheid van de inwoners.'], ['Professionele groei', 'Echte mogelijkheden voor promotie en voortdurende ontwikkeling.'], ['Hart van Europa', 'Een gunstige ligging met gemakkelijke toegang tot het hele continent.']] }
    }
  },

  es: {
    topTagline: 'Confianza. Cuidado. Futuro.', location: 'Varsovia, Polonia',
    nav: { home: 'Inicio', about: 'Sobre nosotros', institutions: 'Para instituciones', candidates: 'Para profesionales', academy: 'Academia', housing: 'Viviendas', poland: 'Polonia', contact: 'Contacto', portal: 'Portal' },
    hero: { h1: ['Soluciones integrales', 'en atención sanitaria', 'para Polonia'], p: 'Conectamos a especialistas cualificados con instituciones médicas en toda Polonia. Reclutamiento, legalización, alojamiento y apoyo: todo en un solo lugar.', bullets: ['Reclutamiento internacional', 'Legalización y documentos', 'Cursos de polaco', 'Apoyo tras la llegada', 'Alojamiento', 'Integración y adaptación', 'Atención de un coordinador', 'Para profesionales y familias'], btnInst: 'Para instituciones', btnProf: 'Para profesionales', btnMeet: '▣ Reservar una reunión', badge: 'Por amor a las personas, pensando en el futuro' },
    specs: ['Médicos generales', 'Especialistas', 'Dentistas', 'Enfermeros', 'Psicólogos', 'Fisioterapeutas', 'Farmacéuticos', 'Higienistas dentales', 'Cuidadores médicos', 'Y más especialidades'],
    cards: [
      { tag: 'PARA PROFESIONALES', h: 'Trabaja en Polonia con nosotros', items: ['Salario atractivo', 'Trabajo legal y apoyo total', 'Ayuda con el reconocimiento de títulos', 'Alojamiento organizado', 'Apoyo para ti y tu familia'], btn: 'COMIENZA TU FUTURO' },
      { tag: 'PARA INSTITUCIONES', h: 'Soluciones eficaces para su centro', items: ['Selección de candidatos cualificados', 'Formación lingüística y cultural', 'Apoyo en los trámites', 'Reconocimiento de títulos', 'Atención permanente de un coordinador'], btn: 'SOLICITAR UNA OFERTA' },
      { tag: 'ACADEMIA HONOR CARE', h: 'Formación y desarrollo profesional', items: ['Cursos de polaco (A1–B2)', 'Términos y abreviaturas médicas', 'Cultura y sistema laboral en Polonia', 'Preparación para el trabajo', 'Formación en línea desde Colombia'], btn: 'IR A LA ACADEMIA' },
      { tag: 'VIVIENDAS', h: 'Confort y seguridad', items: ['Modernas y totalmente equipadas', 'Cerca del trabajo', 'Apoyo a la integración', 'Seguras y verificadas', 'Para familias e individuos'], btn: 'VER VIVIENDAS' }
    ],
    why: { eyebrow: '¿POR QUÉ POLONIA?', h2: ['Un futuro estable', 'en el corazón de Europa'], p: 'Polonia ofrece excelentes oportunidades de desarrollo profesional, seguridad y una alta calidad de vida.', btn: 'SABER MÁS', stats: ['Especialistas ya trabajan en Polonia', 'Centros médicos colaboran con nosotros', 'Años de experiencia en reclutamiento internacional', 'Países unidos por un objetivo'] },
    partnersTitle: 'NUESTROS SOCIOS',
    footer: { tagline: 'Construimos puentes entre Colombia y Polonia, conectando talento, oportunidades y futuro.', quick: 'Enlaces rápidos', officeNL: 'Polonia – Oficina Central', officeCO: 'Colombia', hoursNL: 'Lun – Vie: 9:00 – 17:00', hoursCO: 'Lun – Vie: 8:00 – 16:00', newsletter: 'Boletín', newsletterText: 'Suscríbete para recibir noticias y ofertas.', newsletterPh: 'Tu correo electrónico', rights: 'Todos los derechos reservados.', privacy: 'Política de privacidad', terms: 'Términos' },
    toast: '¡Gracias! Te has suscrito al boletín.',
    notFound: 'Página no encontrada.',
    contactIntro: 'Ponte en contacto con nosotros sobre colaboración o reclutamiento.',
    pages: {
      about: { intro: 'Honor Care International conecta Colombia y Polonia mediante reclutamiento profesional, formación y atención coordinada.', panels: [['Nuestra misión', 'Creamos trayectorias profesionales seguras y dignas para especialistas médicos, respondiendo a las necesidades reales del sistema sanitario polaco.'], ['Dos países, un objetivo', 'Operamos en Colombia y Polonia, combinando el reclutamiento en origen con un apoyo completo sobre el terreno.'], ['El recorrido completo', 'Desde la selección y la verificación de títulos, pasando por el aprendizaje del idioma, hasta el alojamiento y la integración: acompañamos al candidato en cada etapa.'], ['Valores', 'La confianza, la transparencia y el respeto por las personas son la base de cada colaboración.'], ['Cumplimiento legal', 'Trabajamos conforme a la legislación laboral polaca, las normas de legalización de residencia y el RGPD.'], ['Por qué nosotros', 'Un único socio responsable de todo el proceso, sin intermediarios ni sorpresas.']] },
      institutions: { intro: 'Ayudamos a los centros médicos de Polonia a resolver eficazmente la escasez de personal.', panels: [['Análisis de necesidades', 'Definimos el perfil de los especialistas requeridos, las cantidades y el calendario de implementación.'], ['Selección de candidatos', 'Presentamos únicamente candidatos verificados con cualificaciones confirmadas.'], ['Legalización y documentos', 'Nos encargamos de los trámites de visado, residencia y reconocimiento de títulos.'], ['Formación lingüística', 'Los candidatos aprenden polaco y terminología médica antes incluso de llegar.'], ['Alojamiento', 'Organizamos alojamientos cómodos cerca del lugar de trabajo.'], ['Atención permanente de un coordinador', 'Un coordinador dedicado apoya al centro y al empleado durante toda la colaboración.']] },
      candidates: { intro: 'Creamos un camino seguro hacia el trabajo en Polonia para profesionales médicos de Colombia.', panels: [['Proceso de reclutamiento', 'Selección transparente y condiciones claras de colaboración desde el primer contacto.'], ['Reconocimiento de títulos', 'Ayudamos con la homologación del título y la confirmación de las competencias profesionales.'], ['Aprendizaje del idioma', 'Cursos de polaco del nivel A1 al B2, con terminología médica.'], ['Llegada y adaptación', 'Apoyo con la mudanza, los trámites y los primeros pasos en Polonia.'], ['Alojamiento', 'Apartamentos amueblados y listos en ubicaciones seguras.'], ['Apoyo familiar', 'Ayuda con la integración familiar, la escolarización de los niños y los asuntos cotidianos.']] },
      academy: { intro: 'La Academia Honor Care prepara a los candidatos lingüística, profesional y culturalmente.', panels: [['Curso A1–A2', 'Conceptos básicos de polaco oral y escrito, listos para situaciones cotidianas.'], ['Curso B1–B2', 'Comunicación avanzada esencial para trabajar con pacientes y equipos.'], ['Terminología médica', 'Vocabulario especializado para enfermeros, médicos y cuidadores.'], ['Formación en línea', 'Aprendizaje flexible a distancia incluso antes de llegar a Polonia.'], ['Exámenes y certificados', 'Preparación para exámenes de idioma y certificados reconocidos.'], ['Mentoría', 'Apoyo individual de un mentor durante todo el aprendizaje.']] },
      housing: { intro: 'Organizamos alojamientos cómodos y apoyo a la integración.', panels: [['Apartamentos modernos', 'Espacios cómodos y totalmente equipados, listos para la llegada.'], ['Ubicación', 'Cerca del trabajo y del transporte público.'], ['Para familias', 'Viviendas adaptadas a las necesidades de familias con niños.'], ['Mobiliario', 'Mobiliario y equipamiento completos desde el primer día.'], ['Apoyo administrativo', 'Ayuda con los contratos, los suministros y el empadronamiento.'], ['Seguridad', 'Barrios seguros y verificados y arrendadores fiables.']] },
      poland: { intro: 'Polonia ofrece estabilidad, desarrollo profesional y una alta calidad de vida.', panels: [['Economía estable', 'Uno de los mercados laborales de más rápido crecimiento de Europa.'], ['Sistema sanitario', 'Demanda creciente de personal médico cualificado.'], ['Calidad de vida', 'Seguridad, buena infraestructura y un coste de vida asequible.'], ['Cultura', 'Rica historia y la apertura y calidez de sus habitantes.'], ['Desarrollo profesional', 'Caminos reales de promoción y mejora continua.'], ['Centro de Europa', 'Una ubicación cómoda con fácil acceso a todo el continente.']] }
    }
  }
};

module.exports = { LANGS, LANGMETA, T };
