// Meertaligheid voor de publieke site: PL (bron), EN, NL, ES.
const LANGS = ['pl', 'en', 'nl', 'es'];
const LANGMETA = {
  pl: { flag: '🇵🇱', label: 'PL', name: 'Polski' },
  en: { flag: '🇬🇧', label: 'EN', name: 'English' },
  nl: { flag: '🇳🇱', label: 'NL', name: 'Nederlands' },
  es: { flag: '🇪🇸', label: 'ES', name: 'Español' }
};

const T = {
  pl: {
    topTagline: 'Zaufanie. Opieka. Przyszłość.', location: 'Bussum, Holandia',
    nav: { home: 'Strona główna', about: 'O nas', institutions: 'Dla instytucji', candidates: 'Dla profesjonalistów', academy: 'Akademia', housing: 'Mieszkania', poland: 'Holandia', contact: 'Kontakt', portal: 'Moje konto' },
    hero: { h1: ['Kompleksowe', 'rozwiązania w opiece zdrowotnej', 'dla Holandii'], p: 'Wspieramy profesjonalistów medycznych z Kolumbii i Hiszpanii w drodze do kariery w holenderskiej ochronie zdrowia: rekrutacja, język niderlandzki (NT2), uznanie dyplomu i rejestracja BIG, przygotowanie i wsparcie. Oficjalne zatrudnienie realizuje nasze zarejestrowane biuro partnerskie. Polska dołączy jako drugi rynek.', bullets: ['Rekrutacja międzynarodowa', 'Legalizacja i dokumenty', 'Kursy języka niderlandzkiego (NT2)', 'Wsparcie po przyjeździe', 'Zakwaterowanie', 'Integracja i adaptacja', 'Opieka koordynatora', 'Dla profesjonalistów i rodzin'], btnInst: 'Dla instytucji', btnProf: 'Dla profesjonalistów', btnMeet: '▣ Umów spotkanie', badge: 'Z miłości do ludzi, z myślą o przyszłości' },
    specs: ['Lekarze ogólni', 'Specjaliści', 'Stomatolodzy', 'Pielęgniarki', 'Psycholodzy', 'Fizjoterapeuci', 'Farmaceuci', 'Ratownicy medyczni', 'Opiekunowie medyczni', 'I więcej specjalizacji'],
    cards: [
      { tag: 'DLA PROFESJONALISTÓW', h: 'Pracuj w Polsce z nami', items: ['Atrakcyjne zarobki', 'Legalna praca i pełne wsparcie', 'Pomoc w uznaniu kwalifikacji', 'Organizacja zakwaterowania', 'Wsparcie dla Ciebie i Twojej rodziny'], btn: 'ZACZNIJ SWOJĄ PRZYSZŁOŚĆ' },
      { tag: 'DLA INSTYTUCJI', h: 'Skuteczne rozwiązania dla Twojej placówki', items: ['Selekcja wykwalifikowanych kandydatów', 'Szkolenia językowe i kulturowe', 'Wsparcie w formalnościach', 'Uznanie kwalifikacji', 'Stała opieka koordynatora'], btn: 'POPROŚ O OFERTĘ' },
      { tag: 'AKADEMIA HONOR CARE', h: 'Szkolenia i rozwój zawodowy', items: ['Kursy języka niderlandzkiego (A1–B2, NT2)', 'Terminy i skróty medyczne', 'Kultura i system pracy w Holandii', 'Przygotowanie do BIG i pracy', 'Szkolenia online z Kolumbii'], btn: 'PRZEJDŹ DO AKADEMII' },
      { tag: 'MIESZKANIA', h: 'Komfort i bezpieczeństwo', items: ['Nowoczesne i w pełni wyposażone', 'Blisko miejsc pracy', 'Wsparcie w integracji', 'Bezpieczne i sprawdzone', 'Dla rodzin i osób indywidualnych'], btn: 'ZOBACZ MIESZKANIA' }
    ],
    why: { eyebrow: 'DLACZEGO HOLANDIA?', h2: ['Stabilna przyszłość', 'w holenderskiej ochronie zdrowia'], p: 'Holandia oferuje świetne warunki pracy, bezpieczeństwo i wysoką jakość życia. Polska dołączy jako drugi rynek.', btn: 'DOWIEDZ SIĘ WIĘCEJ', stats: [['Pełne wsparcie', 'Od rekrutacji po integrację — wszystko w jednym miejscu.'], ['Dla instytucji', 'Jeden zaufany partner dla Twoich potrzeb kadrowych.'], ['Etyczna rekrutacja', 'Uczciwie i przejrzyście, zgodnie z kodeksem WHO.'], ['Trzy kraje, jeden cel', 'Łączymy Kolumbię, Hiszpanię i Holandię.']] },
    partnersTitle: 'NASI PARTNERZY',
    footer: { tagline: 'Budujemy mosty między Kolumbią, Hiszpanią a Holandią, łącząc talenty, możliwości i przyszłość.', quick: 'Szybkie linki', officeNL: 'Holandia – Biuro Główne', officePL: 'Polska – Biuro', hoursNL: 'Pon – Pt: 9:00 – 17:00', hoursPL: 'Pon – Pt: 8:00 – 16:00', newsletter: 'Newsletter', newsletterText: 'Zapisz się, aby otrzymywać aktualności i oferty.', newsletterPh: 'Twój e-mail', rights: 'Wszelkie prawa zastrzeżone.', privacy: 'Polityka prywatności', terms: 'Regulamin' },
    toast: 'Dziękujemy! Zapisano do newslettera.',
    notFound: 'Strona nie została znaleziona.',
    contactIntro: 'Skontaktuj się z nami w sprawie współpracy lub rekrutacji.',
    pages: {
      about: { intro: 'Honor Care International łączy Kolumbię, Hiszpanię i Holandię poprzez profesjonalną rekrutację, edukację i opiekę koordynacyjną.', panels: [['Nasza misja', 'Tworzymy bezpieczne i godne ścieżki kariery dla specjalistów medycznych, odpowiadając na realne potrzeby holenderskiego systemu opieki zdrowotnej.'], ['Trzy kraje, jeden cel', 'Działamy w Kolumbii, Hiszpanii i w Holandii, łącząc rekrutację u źródła z pełnym wsparciem na miejscu.'], ['Pełna ścieżka', 'Od selekcji i weryfikacji dyplomów, przez naukę języka, aż po zakwaterowanie i integrację — prowadzimy kandydata na każdym etapie.'], ['Wartości', 'Zaufanie, transparentność i szacunek dla człowieka są fundamentem każdej współpracy.'], ['Zgodność prawna', 'Pracujemy zgodnie z holenderskim prawem (Waadi/Wtta, ustawa BIG), przepisami pobytowymi oraz RODO.'], ['Dlaczego my', 'Jeden partner odpowiedzialny za cały proces — bez pośredników i bez niespodzianek.']] },
      institutions: { intro: 'Pomagamy placówkom medycznym w Holandii skutecznie rozwiązać braki kadrowe.', panels: [['Analiza potrzeb', 'Określamy profil poszukiwanych specjalistów, liczebność i harmonogram wdrożenia.'], ['Selekcja kandydatów', 'Prezentujemy wyłącznie zweryfikowanych kandydatów z potwierdzonymi kwalifikacjami.'], ['Legalizacja i dokumenty', 'Przejmujemy formalności wizowe, pobytowe i związane z uznaniem kwalifikacji.'], ['Szkolenia językowe', 'Kandydaci uczą się języka niderlandzkiego i terminologii medycznej jeszcze przed przyjazdem.'], ['Zakwaterowanie', 'Organizujemy komfortowe mieszkania blisko miejsca pracy.'], ['Stała opieka koordynatora', 'Dedykowany koordynator wspiera placówkę i pracownika przez cały okres współpracy.'], ['Szybsza obsada z UE', 'Kandydaci z Hiszpanii i innych krajów UE nie wymagają wizy ani zezwolenia na pracę; o długości procesu decydują głównie język i uznanie BIG. Dzięki temu wakaty obsadzasz wyraźnie szybciej niż spoza UE.']] },
      candidates: { intro: 'Tworzymy bezpieczną drogę do pracy w Holandii dla profesjonalistów medycznych z Kolumbii i Hiszpanii.', panels: [['Z Hiszpanii lub innego kraju UE', 'Obywatele UE nie potrzebują wizy ani zezwolenia na pracę. Dyplom trzeba uznać w rejestrze BIG, a udokumentowany niderlandzki jest warunkiem koniecznym. Prowadzimy Cię przez obie sprawy.'], ['Proces rekrutacji', 'Przejrzysta selekcja i jasne warunki współpracy od pierwszego kontaktu.'], ['Uznanie kwalifikacji', 'Pomagamy w uznaniu dyplomu, egzaminie BI-toets i rejestracji BIG.'], ['Nauka języka', 'Kursy niderlandzkiego od A1 do B2 (NT2) wraz z terminologią medyczną.'], ['Przyjazd i adaptacja', 'Wsparcie przy przeprowadzce, formalnościach i pierwszych krokach w Holandii.'], ['Zakwaterowanie', 'Gotowe, umeblowane mieszkania w bezpiecznych lokalizacjach.'], ['Wsparcie rodziny', 'Pomoc w integracji rodziny, szkole dla dzieci i codziennych sprawach.']] },
      academy: { intro: 'Akademia Honor Care przygotowuje kandydatów językowo, zawodowo i kulturowo.', panels: [['Kurs A1–A2', 'Podstawy języka niderlandzkiego w mowie i piśmie, gotowe na codzienne sytuacje.'], ['Kurs B1–B2', 'Zaawansowana komunikacja niezbędna w pracy z pacjentem i zespołem.'], ['Terminologia medyczna', 'Specjalistyczne słownictwo dla pielęgniarek, lekarzy i opiekunów.'], ['Szkolenia online', 'Elastyczna nauka zdalna jeszcze przed przyjazdem do Holandii.'], ['Egzaminy i certyfikaty', 'Przygotowanie do egzaminu NT2 i rejestracji BIG.'], ['Mentoring', 'Indywidualne wsparcie mentora przez cały okres nauki.']] },
      housing: { intro: 'Organizujemy komfortowe mieszkania i wsparcie integracyjne.', panels: [['Załatwione przed wyjazdem', 'Mieszkanie czeka na Ciebie po przyjeździe — nigdy nie jedziesz bez adresu. W pierwszym okresie to zwykle mieszkanie dzielone z kolegami, w pełni umeblowane.'], ['Lokalizacja', 'Blisko miejsc pracy i komunikacji miejskiej.'], ['Przyjeżdżasz z rodziną?', 'Zgłoś to wcześnie. Odpowiednich mieszkań rodzinnych w Holandii brakuje i wymagają znacznie więcej czasu na przygotowanie.'], ['Umeblowanie', 'Pełne umeblowanie i wyposażenie od pierwszego dnia.'], ['Wsparcie administracyjne', 'Pomoc przy umowach, mediach i meldunku.'], ['Bezpieczeństwo', 'Sprawdzone, bezpieczne dzielnice i rzetelni wynajmujący.']] },
      poland: { intro: 'Holandia oferuje stabilność, rozwój zawodowy i wysoką jakość życia. Polska dołączy jako drugi rynek.', panels: [['Stabilna gospodarka', 'Jeden z najszybciej rozwijających się rynków pracy w Europie.'], ['System opieki zdrowotnej', 'Rosnące zapotrzebowanie na wykwalifikowany personel medyczny.'], ['Jakość życia', 'Bezpieczeństwo, dobra infrastruktura i przystępne koszty życia.'], ['Kultura', 'Bogata historia, otwartość i serdeczność mieszkańców.'], ['Rozwój zawodowy', 'Realne ścieżki awansu i stałego doskonalenia.'], ['Centrum Europy', 'Dogodna lokalizacja i łatwy dostęp do całego kontynentu.']] }
    }
  },

  en: {
    topTagline: 'Trust. Care. Future.', location: 'Bussum, Netherlands',
    nav: { home: 'Home', about: 'About us', institutions: 'For institutions', candidates: 'For professionals', academy: 'Academy', housing: 'Housing', poland: 'Netherlands', contact: 'Contact', portal: 'My account' },
    hero: { h1: ['Comprehensive', 'healthcare solutions', 'for the Netherlands'], p: 'We guide healthcare professionals from Colombia and Spain toward a career in Dutch healthcare: sourcing, Dutch (NT2), diploma recognition and BIG registration, preparation and support. The official placement is handled by our registered partner agency. Poland will follow as a second market.', bullets: ['International recruitment', 'Legalisation & documents', 'Dutch courses (NT2)', 'Post-arrival support', 'Housing', 'Integration & adaptation', 'Coordinator care', 'For professionals & families'], btnInst: 'For institutions', btnProf: 'For professionals', btnMeet: '▣ Book a meeting', badge: 'Out of love for people, with the future in mind' },
    specs: ['General practitioners', 'Specialists', 'Dentists', 'Nurses', 'Psychologists', 'Physiotherapists', 'Pharmacists', 'Paramedics', 'Medical caregivers', 'And more specialties'],
    cards: [
      { tag: 'FOR PROFESSIONALS', h: 'Work in the Netherlands with us', items: ['Attractive salary', 'Legal work and full support', 'Help with diploma recognition and BIG', 'Housing arranged for you', 'Support for you and your family'], btn: 'START YOUR FUTURE' },
      { tag: 'FOR INSTITUTIONS', h: 'Effective solutions for your facility', items: ['Selection of qualified candidates', 'Language and cultural training', 'Support with formalities', 'Recognition of qualifications', 'Ongoing coordinator support'], btn: 'REQUEST AN OFFER' },
      { tag: 'HONOR CARE ACADEMY', h: 'Training and professional development', items: ['Dutch courses (A1–B2, NT2)', 'Medical terms and abbreviations', 'Dutch work culture and healthcare system', 'BIG and job preparation', 'Online training from Colombia'], btn: 'GO TO THE ACADEMY' },
      { tag: 'HOUSING', h: 'Comfort and safety', items: ['Modern and fully furnished', 'Close to workplaces', 'Integration support', 'Safe and verified', 'For families and individuals'], btn: 'VIEW HOUSING' }
    ],
    why: { eyebrow: 'WHY THE NETHERLANDS?', h2: ['A stable future', 'in Dutch healthcare'], p: 'The Netherlands offers healthcare professionals excellent working conditions, safety and a high quality of life. Poland will follow as a second market.', btn: 'LEARN MORE', stats: [['Full support', 'From recruitment to integration — all in one place.'], ['For institutions', 'One trusted partner for your staffing needs.'], ['Ethical recruitment', 'Fair and transparent, following the WHO code.'], ['Three countries, one goal', 'We connect Colombia, Spain and the Netherlands.']] },
    partnersTitle: 'OUR PARTNERS',
    footer: { tagline: 'We build bridges between Colombia, Spain and the Netherlands, connecting talent, opportunity and the future.', quick: 'Quick links', officeNL: 'Netherlands – Head Office', officePL: 'Poland – Office', hoursNL: 'Mon – Fri: 9:00 – 17:00', hoursPL: 'Mon – Fri: 8:00 – 16:00', newsletter: 'Newsletter', newsletterText: 'Sign up to receive news and offers.', newsletterPh: 'Your e-mail', rights: 'All rights reserved.', privacy: 'Privacy policy', terms: 'Terms' },
    toast: "Thank you! You're subscribed to the newsletter.",
    notFound: 'Page not found.',
    contactIntro: 'Get in touch with us about cooperation or recruitment.',
    pages: {
      about: { intro: 'Honor Care International connects Colombia, Spain and the Netherlands through professional recruitment, education and coordinated care.', panels: [['Our mission', 'We create safe and dignified career paths for medical specialists, meeting the real needs of the Dutch healthcare system.'], ['Three countries, one goal', 'We operate in Colombia, Spain and the Netherlands, combining recruitment at the source with full on-site support.'], ['The full journey', 'From selection and diploma verification, through language learning, to housing and integration — we guide the candidate at every step.'], ['Values', 'Trust, transparency and respect for people are the foundation of every partnership.'], ['Legal compliance', 'We work in compliance with the Waadi/Wtta, the BIG Act, residence and work rules and the GDPR.'], ['Why us', 'One partner responsible for the entire process — no middlemen, no surprises.']] },
      institutions: { intro: 'We help medical facilities in the Netherlands effectively solve staff shortages.', panels: [['Needs analysis', 'We define the profile of the specialists needed, the numbers and the implementation timeline.'], ['Candidate selection', 'We present only verified candidates with confirmed qualifications.'], ['Legalisation & documents', 'We handle visa, residence and qualification-recognition formalities.'], ['Language training', 'Candidates learn Dutch (NT2) and medical terminology before they even arrive.'], ['Housing', 'We arrange comfortable housing close to the workplace.'], ['Ongoing coordinator support', 'A dedicated coordinator supports the facility and the employee throughout the cooperation.'], ['Faster staffing from the EU', 'Candidates from Spain and other EU countries need no visa or work permit; the timeline is set mainly by language and BIG recognition. That fills vacancies noticeably faster than with candidates from outside the EU.']] },
      candidates: { intro: 'We create a safe path to working in Dutch healthcare for medical professionals from Colombia and Spain.', panels: [['From Spain or another EU country', 'EU citizens need no visa or work permit. Your diploma still needs recognition through the BIG register, and demonstrable Dutch is a hard requirement. We guide you through both.'], ['Recruitment process', 'Transparent selection and clear terms of cooperation from the first contact.'], ['Recognition of qualifications', 'We help with diploma recognition, the BI-toets and BIG registration.'], ['Language learning', 'Dutch courses from A1 to B2 (NT2), including medical terminology.'], ['Arrival & adaptation', 'Support with the move, formalities and your first steps in the Netherlands.'], ['Housing', 'Ready, furnished apartments in safe locations.'], ['Family support', 'Help with family integration, schooling for children and everyday matters.']] },
      academy: { intro: 'The Honor Care Academy prepares candidates linguistically, professionally and culturally.', panels: [['A1–A2 course', 'Dutch basics in speech and writing, ready for everyday situations.'], ['B1–B2 course', 'Advanced communication essential for working with patients and teams.'], ['Medical terminology', 'Specialist vocabulary for nurses, doctors and caregivers.'], ['Online training', 'Flexible remote learning even before arriving in the Netherlands.'], ['Exams & certificates', 'Preparation for the NT2 state exam and BIG.'], ['Mentoring', 'Individual mentor support throughout the learning period.']] },
      housing: { intro: 'We arrange comfortable housing and integration support.', panels: [['Arranged before you travel', 'Your home is ready when you arrive — you never travel without an address. In the first period this is often shared housing with colleagues, fully furnished.'], ['Location', 'Close to workplaces and public transport.'], ['Bringing your family?', 'Raise it early in the process. Suitable family homes are scarce in the Netherlands and need considerably more preparation time.'], ['Furnishing', 'Full furnishing and equipment from day one.'], ['Administrative support', 'Help with contracts, utilities and registration.'], ['Safety', 'Verified, safe neighbourhoods and reliable landlords.']] },
      poland: { intro: 'The Netherlands offers healthcare professionals stability, professional growth and a high quality of life. Poland will follow as a second market.', panels: [['Stable economy', 'One of the fastest-growing labour markets in Europe.'], ['Healthcare system', 'Growing demand for qualified medical staff.'], ['Quality of life', 'Safety, good infrastructure and affordable living costs.'], ['Culture', 'Rich history and the openness and warmth of its people.'], ['Professional growth', 'Real paths for promotion and continuous development.'], ['Heart of Europe', 'A convenient location with easy access to the whole continent.']] }
    }
  },

  nl: {
    topTagline: 'Vertrouwen. Zorg. Toekomst.', location: 'Bussum, Nederland',
    nav: { home: 'Home', about: 'Over ons', institutions: 'Voor instellingen', candidates: 'Voor professionals', academy: 'Academie', housing: 'Huisvesting', poland: 'Nederland', contact: 'Contact', portal: 'Mijn account' },
    hero: { h1: ['Complete', 'zorgoplossingen', 'voor Nederland'], p: 'Wij begeleiden zorgprofessionals uit Colombia en Spanje naar een carrière in de Nederlandse zorg: werving, Nederlands (NT2), diploma-erkenning en BIG-registratie, voorbereiding en begeleiding. De officiële plaatsing verloopt via ons geregistreerde partnerbureau. Polen volgt als tweede markt.', bullets: ['Internationale werving', 'Legalisatie & documenten', 'Cursussen Nederlands (NT2)', 'Begeleiding na aankomst', 'Huisvesting', 'Integratie & aanpassing', 'Zorg van een coördinator', 'Voor professionals & gezinnen'], btnInst: 'Voor instellingen', btnProf: 'Voor professionals', btnMeet: '▣ Plan een gesprek', badge: 'Uit liefde voor mensen, met het oog op de toekomst' },
    specs: ['Huisartsen', 'Specialisten', 'Tandartsen', 'Verpleegkundigen', 'Psychologen', 'Fysiotherapeuten', 'Apothekers', 'Ambulanceverpleegkundigen', 'Zorgverleners', 'En meer specialismen'],
    cards: [
      { tag: 'VOOR PROFESSIONALS', h: 'Werk met ons in Nederland', items: ['Aantrekkelijk salaris', 'Legaal werk en volledige begeleiding', 'Hulp bij diploma-erkenning en BIG', 'Huisvesting geregeld', 'Steun voor jou en je gezin'], btn: 'START JE TOEKOMST' },
      { tag: 'VOOR INSTELLINGEN', h: 'Doeltreffende oplossingen voor uw instelling', items: ['Selectie van gekwalificeerde kandidaten', 'Taal- en cultuurtraining', 'Ondersteuning bij formaliteiten', 'Erkenning van kwalificaties', 'Vaste begeleiding door coördinator'], btn: 'VRAAG EEN OFFERTE AAN' },
      { tag: 'HONOR CARE ACADEMIE', h: 'Training en professionele ontwikkeling', items: ['Cursussen Nederlands (A1–B2, NT2)', 'Medische termen en afkortingen', 'Werkcultuur en zorgstelsel in Nederland', 'Voorbereiding op BIG en werk', 'Online training vanuit Colombia'], btn: 'NAAR DE ACADEMIE' },
      { tag: 'HUISVESTING', h: 'Comfort en veiligheid', items: ['Modern en volledig ingericht', 'Dicht bij het werk', 'Ondersteuning bij integratie', 'Veilig en gecontroleerd', 'Voor gezinnen en alleenstaanden'], btn: 'BEKIJK WONINGEN' }
    ],
    why: { eyebrow: 'WAAROM NEDERLAND?', h2: ['Een stabiele toekomst', 'in de Nederlandse zorg'], p: 'Nederland biedt zorgprofessionals uitstekende arbeidsvoorwaarden, veiligheid en een hoge levenskwaliteit. Polen volgt als tweede markt.', btn: 'MEER WETEN', stats: [['Volledige begeleiding', 'Van werving tot integratie — alles in één hand.'], ['Voor zorginstellingen', 'Eén betrouwbaar aanspreekpunt voor uw personeelsvraag.'], ['Ethische werving', 'Eerlijk en transparant, volgens de WHO-gedragscode.'], ['Drie landen, één doel', 'Wij verbinden Colombia, Spanje en Nederland.']] },
    partnersTitle: 'ONZE PARTNERS',
    footer: { tagline: 'Wij bouwen bruggen tussen Colombia, Spanje en Nederland en verbinden talent, kansen en toekomst.', quick: 'Snelle links', officeNL: 'Nederland – Hoofdkantoor', officePL: 'Polen – Kantoor', hoursNL: 'Ma – Vr: 9:00 – 17:00', hoursPL: 'Ma – Vr: 8:00 – 16:00', newsletter: 'Nieuwsbrief', newsletterText: 'Schrijf je in voor nieuws en aanbiedingen.', newsletterPh: 'Je e-mail', rights: 'Alle rechten voorbehouden.', privacy: 'Privacybeleid', terms: 'Voorwaarden' },
    toast: 'Bedankt! Je bent ingeschreven voor de nieuwsbrief.',
    notFound: 'Pagina niet gevonden.',
    contactIntro: 'Neem contact met ons op over samenwerking of werving.',
    pages: {
      about: { intro: 'Honor Care International verbindt Colombia, Spanje en Nederland via professionele werving, opleiding en gecoördineerde begeleiding.', panels: [['Onze missie', 'Wij creëren veilige en waardige loopbaanpaden voor medische specialisten en spelen in op de werkelijke behoeften van de Nederlandse zorg.'], ['Drie landen, één doel', 'We zijn actief in Colombia, Spanje en Nederland en combineren werving aan de bron met volledige ondersteuning ter plaatse.'], ['Het volledige traject', 'Van selectie en diplomacontrole, via taalverwerving, tot huisvesting en integratie — we begeleiden de kandidaat in elke fase.'], ['Waarden', 'Vertrouwen, transparantie en respect voor de mens vormen de basis van elke samenwerking.'], ['Juridische naleving', 'We werken conform de Waadi/Wtta, de Wet BIG, de verblijfs- en arbeidsregels en de AVG.'], ['Waarom wij', 'Eén partner verantwoordelijk voor het hele proces — geen tussenpersonen, geen verrassingen.']] },
      institutions: { intro: 'Wij helpen zorginstellingen in Nederland personeelstekorten doeltreffend op te lossen.', panels: [['Behoefteanalyse', 'We bepalen het profiel van de gezochte specialisten, de aantallen en de planning.'], ['Kandidaatselectie', 'We presenteren uitsluitend geverifieerde kandidaten met bevestigde kwalificaties.'], ['Legalisatie & documenten', 'Wij nemen de visum-, verblijfs- en diploma-erkenningsformaliteiten over.'], ['Taaltraining', 'Kandidaten leren Nederlands (NT2) en medische terminologie nog vóór hun aankomst.'], ['Huisvesting', 'Wij regelen comfortabele woningen dicht bij het werk.'], ['Vaste begeleiding door coördinator', 'Een vaste coördinator ondersteunt de instelling en de medewerker gedurende de hele samenwerking.'], ['Sneller invullen met EU-kandidaten', 'Kandidaten uit Spanje en andere EU-landen hebben geen visum of tewerkstellingsvergunning nodig; de doorlooptijd wordt vooral bepaald door taal en BIG-erkenning. Daardoor vult u vacatures merkbaar sneller dan met kandidaten van buiten de EU.']] },
      candidates: { intro: 'Wij creëren een veilige weg naar werk in de Nederlandse zorg voor medische professionals uit Colombia en Spanje.', panels: [['Uit Spanje of een ander EU-land', 'EU-burgers hebben geen visum of tewerkstellingsvergunning nodig. Je diploma moet wel erkend worden via het BIG-register, en aantoonbaar Nederlands is daarbij een harde voorwaarde. Wij begeleiden je bij allebei.'], ['Wervingsproces', 'Transparante selectie en duidelijke samenwerkingsvoorwaarden vanaf het eerste contact.'], ['Erkenning van kwalificaties', 'Wij helpen bij diploma-erkenning, de BI-toets en BIG-registratie.'], ['Taal leren', 'Cursussen Nederlands van A1 tot B2 (NT2), inclusief medische terminologie.'], ['Aankomst & aanpassing', 'Begeleiding bij de verhuizing, formaliteiten en eerste stappen in Nederland.'], ['Huisvesting', 'Kant-en-klare, gemeubileerde woningen op veilige locaties.'], ['Gezinsondersteuning', 'Hulp bij gezinsintegratie, school voor de kinderen en dagelijkse zaken.']] },
      academy: { intro: 'De Honor Care Academie bereidt kandidaten talig, professioneel en cultureel voor.', panels: [['Cursus A1–A2', 'Basis Nederlands in spraak en schrift, klaar voor dagelijkse situaties.'], ['Cursus B1–B2', 'Gevorderde communicatie die nodig is in het werk met patiënten en team.'], ['Medische terminologie', 'Vakspecifiek vocabulaire voor verpleegkundigen, artsen en verzorgenden.'], ['Online training', 'Flexibel leren op afstand, nog vóór de aankomst in Nederland.'], ['Examens & certificaten', 'Voorbereiding op het NT2-staatsexamen en BIG.'], ['Mentoring', 'Individuele mentorbegeleiding gedurende de hele opleiding.']] },
      housing: { intro: 'Wij regelen comfortabele woningen en integratieondersteuning.', panels: [['Geregeld vóór je vertrek', 'Je woning staat klaar als je aankomt — je reist nooit zonder adres. In de eerste periode is dat vaak gedeelde huisvesting met collega’s, volledig ingericht.'], ['Locatie', 'Dicht bij het werk en openbaar vervoer.'], ['Kom je met je gezin?', 'Bespreek dat vroeg in het traject. Passende gezinswoningen zijn schaars in Nederland en vragen aanzienlijk meer voorbereidingstijd.'], ['Inrichting', 'Volledige inrichting en uitrusting vanaf dag één.'], ['Administratieve ondersteuning', 'Hulp bij contracten, nutsvoorzieningen en inschrijving.'], ['Veiligheid', 'Gecontroleerde, veilige buurten en betrouwbare verhuurders.']] },
      poland: { intro: 'Nederland biedt zorgprofessionals stabiliteit, professionele groei en een hoge levenskwaliteit. Polen volgt als tweede markt.', panels: [['Stabiele economie', 'Een van de snelst groeiende arbeidsmarkten van Europa.'], ['Zorgstelsel', 'Groeiende vraag naar gekwalificeerd medisch personeel.'], ['Levenskwaliteit', 'Veiligheid, goede infrastructuur en betaalbare kosten van levensonderhoud.'], ['Cultuur', 'Rijke geschiedenis en de openheid en hartelijkheid van de inwoners.'], ['Professionele groei', 'Echte mogelijkheden voor promotie en voortdurende ontwikkeling.'], ['Hart van Europa', 'Een gunstige ligging met gemakkelijke toegang tot het hele continent.']] }
    }
  },

  es: {
    topTagline: 'Confianza. Cuidado. Futuro.', location: 'Bussum, Países Bajos',
    nav: { home: 'Inicio', about: 'Sobre nosotros', institutions: 'Para instituciones', candidates: 'Para profesionales', academy: 'Academia', housing: 'Viviendas', poland: 'Países Bajos', contact: 'Contacto', portal: 'Mi cuenta' },
    hero: { h1: ['Soluciones integrales', 'en atención sanitaria', 'para los Países Bajos'], p: 'Acompañamos a profesionales sanitarios de Colombia y España hacia una carrera en la sanidad neerlandesa: captación, neerlandés (NT2), homologación del título y registro BIG, preparación y apoyo. La colocación oficial se realiza a través de nuestra agencia asociada registrada. Polonia llegará como segundo mercado.', bullets: ['Reclutamiento internacional', 'Legalización y documentos', 'Cursos de neerlandés (NT2)', 'Apoyo tras la llegada', 'Alojamiento', 'Integración y adaptación', 'Atención de un coordinador', 'Para profesionales y familias'], btnInst: 'Para instituciones', btnProf: 'Para profesionales', btnMeet: '▣ Reservar una reunión', badge: 'Por amor a las personas, pensando en el futuro' },
    specs: ['Médicos generales', 'Especialistas', 'Dentistas', 'Enfermeros', 'Psicólogos', 'Fisioterapeutas', 'Farmacéuticos', 'Paramédicos', 'Cuidadores médicos', 'Y más especialidades'],
    cards: [
      { tag: 'PARA PROFESIONALES', h: 'Trabaja en los Países Bajos con nosotros', items: ['Salario atractivo', 'Trabajo legal y apoyo total', 'Ayuda con la homologación y el registro BIG', 'Alojamiento organizado', 'Apoyo para ti y tu familia'], btn: 'COMIENZA TU FUTURO' },
      { tag: 'PARA INSTITUCIONES', h: 'Soluciones eficaces para su centro', items: ['Selección de candidatos cualificados', 'Formación lingüística y cultural', 'Apoyo en los trámites', 'Reconocimiento de títulos', 'Atención permanente de un coordinador'], btn: 'SOLICITAR UNA OFERTA' },
      { tag: 'ACADEMIA HONOR CARE', h: 'Formación y desarrollo profesional', items: ['Cursos de neerlandés (A1–B2, NT2)', 'Términos y abreviaturas médicas', 'Cultura y sistema sanitario en los Países Bajos', 'Preparación para el BIG y el trabajo', 'Formación en línea desde Colombia'], btn: 'IR A LA ACADEMIA' },
      { tag: 'VIVIENDAS', h: 'Confort y seguridad', items: ['Modernas y totalmente equipadas', 'Cerca del trabajo', 'Apoyo a la integración', 'Seguras y verificadas', 'Para familias e individuos'], btn: 'VER VIVIENDAS' }
    ],
    why: { eyebrow: '¿POR QUÉ LOS PAÍSES BAJOS?', h2: ['Un futuro estable', 'en la sanidad neerlandesa'], p: 'Los Países Bajos ofrecen excelentes condiciones laborales, seguridad y una alta calidad de vida. Polonia llegará como segundo mercado.', btn: 'SABER MÁS', stats: [['Apoyo completo', 'De la selección a la integración, todo en un solo lugar.'], ['Para instituciones', 'Un socio de confianza para sus necesidades de personal.'], ['Reclutamiento ético', 'Justo y transparente, según el código de la OMS.'], ['Tres países, un objetivo', 'Conectamos Colombia, España y los Países Bajos.']] },
    partnersTitle: 'NUESTROS SOCIOS',
    footer: { tagline: 'Construimos puentes entre Colombia, España y los Países Bajos, conectando talento, oportunidades y futuro.', quick: 'Enlaces rápidos', officeNL: 'Países Bajos – Oficina Central', officePL: 'Polonia – Oficina', hoursNL: 'Lun – Vie: 9:00 – 17:00', hoursPL: 'Lun – Vie: 8:00 – 16:00', newsletter: 'Boletín', newsletterText: 'Suscríbete para recibir noticias y ofertas.', newsletterPh: 'Tu correo electrónico', rights: 'Todos los derechos reservados.', privacy: 'Política de privacidad', terms: 'Términos' },
    toast: '¡Gracias! Te has suscrito al boletín.',
    notFound: 'Página no encontrada.',
    contactIntro: 'Ponte en contacto con nosotros sobre colaboración o reclutamiento.',
    pages: {
      about: { intro: 'Honor Care International conecta Colombia, España y los Países Bajos mediante reclutamiento profesional, formación y atención coordinada.', panels: [['Nuestra misión', 'Creamos trayectorias profesionales seguras y dignas para especialistas médicos, respondiendo a las necesidades reales del sistema sanitario neerlandés.'], ['Tres países, un objetivo', 'Operamos en Colombia, España y los Países Bajos, combinando el reclutamiento en origen con un apoyo completo sobre el terreno.'], ['El recorrido completo', 'Desde la selección y la verificación de títulos, pasando por el aprendizaje del idioma, hasta el alojamiento y la integración: acompañamos al candidato en cada etapa.'], ['Valores', 'La confianza, la transparencia y el respeto por las personas son la base de cada colaboración.'], ['Cumplimiento legal', 'Trabajamos conforme a la Waadi/Wtta, la Ley BIG, las normas de residencia y trabajo y el RGPD.'], ['Por qué nosotros', 'Un único socio responsable de todo el proceso, sin intermediarios ni sorpresas.']] },
      institutions: { intro: 'Ayudamos a los centros médicos de los Países Bajos a resolver eficazmente la escasez de personal.', panels: [['Análisis de necesidades', 'Definimos el perfil de los especialistas requeridos, las cantidades y el calendario de implementación.'], ['Selección de candidatos', 'Presentamos únicamente candidatos verificados con cualificaciones confirmadas.'], ['Legalización y documentos', 'Nos encargamos de los trámites de visado, residencia y reconocimiento de títulos.'], ['Formación lingüística', 'Los candidatos aprenden neerlandés (NT2) y terminología médica antes incluso de llegar.'], ['Alojamiento', 'Organizamos alojamientos cómodos cerca del lugar de trabajo.'], ['Atención permanente de un coordinador', 'Un coordinador dedicado apoya al centro y al empleado durante toda la colaboración.'], ['Cobertura más rápida desde la UE', 'Los candidatos de España y otros países de la UE no necesitan visado ni permiso de trabajo; los plazos dependen sobre todo del idioma y del reconocimiento BIG. Así las vacantes se cubren notablemente antes que con candidatos de fuera de la UE.']] },
      candidates: { intro: 'Creamos un camino seguro hacia el trabajo en la sanidad neerlandesa para profesionales médicos de Colombia y España.', panels: [['Desde España u otro país de la UE', 'Los ciudadanos de la UE no necesitan visado ni permiso de trabajo. El título sí debe reconocerse en el registro BIG, y acreditar el neerlandés es un requisito ineludible. Te acompañamos en ambos pasos.'], ['Proceso de reclutamiento', 'Selección transparente y condiciones claras de colaboración desde el primer contacto.'], ['Reconocimiento de títulos', 'Ayudamos con la homologación del título, la BI-toets y el registro BIG.'], ['Aprendizaje del idioma', 'Cursos de neerlandés del nivel A1 al B2 (NT2), con terminología médica.'], ['Llegada y adaptación', 'Apoyo con la mudanza, los trámites y los primeros pasos en los Países Bajos.'], ['Alojamiento', 'Apartamentos amueblados y listos en ubicaciones seguras.'], ['Apoyo familiar', 'Ayuda con la integración familiar, la escolarización de los niños y los asuntos cotidianos.']] },
      academy: { intro: 'La Academia Honor Care prepara a los candidatos lingüística, profesional y culturalmente.', panels: [['Curso A1–A2', 'Conceptos básicos de neerlandés oral y escrito, listos para situaciones cotidianas.'], ['Curso B1–B2', 'Comunicación avanzada esencial para trabajar con pacientes y equipos.'], ['Terminología médica', 'Vocabulario especializado para enfermeros, médicos y cuidadores.'], ['Formación en línea', 'Aprendizaje flexible a distancia incluso antes de llegar a los Países Bajos.'], ['Exámenes y certificados', 'Preparación para el examen estatal NT2 y el BIG.'], ['Mentoría', 'Apoyo individual de un mentor durante todo el aprendizaje.']] },
      housing: { intro: 'Organizamos alojamientos cómodos y apoyo a la integración.', panels: [['Organizado antes de viajar', 'Tu vivienda está lista a tu llegada: nunca viajas sin dirección. En la primera etapa suele ser vivienda compartida con compañeros, totalmente amueblada.'], ['Ubicación', 'Cerca del trabajo y del transporte público.'], ['¿Vienes con tu familia?', 'Coméntalo pronto en el proceso. Las viviendas familiares adecuadas escasean en los Países Bajos y requieren bastante más tiempo de preparación.'], ['Mobiliario', 'Mobiliario y equipamiento completos desde el primer día.'], ['Apoyo administrativo', 'Ayuda con los contratos, los suministros y el empadronamiento.'], ['Seguridad', 'Barrios seguros y verificados y arrendadores fiables.']] },
      poland: { intro: 'Los Países Bajos ofrecen estabilidad, desarrollo profesional y una alta calidad de vida. Polonia llegará como segundo mercado.', panels: [['Economía estable', 'Uno de los mercados laborales de más rápido crecimiento de Europa.'], ['Sistema sanitario', 'Demanda creciente de personal médico cualificado.'], ['Calidad de vida', 'Seguridad, buena infraestructura y un coste de vida asequible.'], ['Cultura', 'Rica historia y la apertura y calidez de sus habitantes.'], ['Desarrollo profesional', 'Caminos reales de promoción y mejora continua.'], ['Centro de Europa', 'Una ubicación cómoda con fácil acceso a todo el continente.']] }
    }
  }
};

module.exports = { LANGS, LANGMETA, T };
